variables:
  # general
  CONFIG_PATH: ".env"
  JWT_ROLE: "gitlab-fe"
  # for eks only:
  # INGRESS: "TRUE"
  # NAMESPACE: "core"
  # for ec2 only:
  NODEJS_VERSION: "17.0.1"
  HOME_APP: "/app"
  DEPLOY_TO: "ec2"
  PROC_MAN: "pm2"
  ARTIFACT_PATH: "artifacts/${CI_PROJECT_NAME}.tar.gz"
  DEPLOYMENT_STRATEGY: "in_place"
  CODE_BASE: "NODEJS"
  RUN_COMMAND: "pm2 start ecosystem.config.js --env production"
  CLUSTER: "ON"


stages:
  - check
  - sast_scan
  - build
  - development
  - staging
  - production
  - deployment
  - config_automation_test
  - automation_test
  - alert

build:
  image:
    name: harbor.linkaja.com/devops/node:$NODEJS_VERSION
    entrypoint: [""]
  stage: build
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - rm -rf ${ARTIFACT_PATH}
    - npm install --force
    - npm run next:build
    - npm install mquery
    - mkdir -p $CI_PROJECT_DIR/artifacts
    - >
        tar -czvf ${ARTIFACT_PATH}
        --exclude=artifacts --exclude=.git --exclude=.gitlab-ci.yml --exclude=Dockerfile --exclude=env.*
        --exclude=*.j2 --exclude=*.tar.gz --exclude=.gitignore --exclude=Makefile --exclude=*.md .
  artifacts:
    expire_in: 1 month
    paths:
      - $ARTIFACT_PATH
  only:
    refs:
      - development
      - /(([a-zA-Z0-99]+)(\W)?([a-zA-Z0-99]+))-v([0-9]|[1-9][0-9]|[1-9][0-9][0-9]).([0-9]|[1-9][0-9]|[1-9][0-9][0-9]).([0-9]|[1-9][0-9]|[1-9][0-9][0-9])/
      - /release-([0-9]|[1-9][0-9]|[1-9][0-9][0-9]).([0-9]|[1-9][0-9]|[1-9][0-9][0-9]).([0-9]|[1-9][0-9]|[1-9][0-9][0-9])/

include:
  - project: 'automation/pipelines'
    ref: 'pipelines-v1.0.15'
    file: 'cd-gitlab-ci.yml'
