const colors = require('tailwindcss/colors')

module.exports = {
  purge: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      black: colors.black,
      white: colors.white,
      gray: colors.trueGray,
      indigo: colors.indigo,
      blue: colors.blue,
      red: colors.rose,
      yellow: colors.amber,
      pink: colors.pink,
      green: colors.green,
      ruby: {
        light: '#FFEAEA',
        base: '#E3292B',
        secondary: '#BC040E',
      },
      tosca: '#0CC5AA',
      carbon: {
        light: '#E7E8F3',
        base: '#656D86',
      },
      whitebase: '#fbfbfb',
      blackbase: '#383838',
      redbase: '#E12A2A',
      reddark: '#E3292B',
      fair: '#EFEFF7',
      pearlsoft: '#E7E8F3',
      pearlheavy: '#F8F8FC',
      pearlroot: '#989EB8',
      blackroot: '#656D86',
      blackmassive: '#001122',
      blackheavy: '#0B1726',
      blueheavy: '#0095C2',
      linkajared: '#E3292B',
      linkajatosca: '#00A796',
      linkajablack: '#19202D',
      icongrey: '#bdbdbd',
    },
    fontFamily: {
      sans: [
        'Mulish',
        'sans-serif',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
      ],
      title: ['Mulish', 'sans-serif', 'ui-sans-serif', 'system-ui', '-apple-system'],
      serif: ['ui-serif', 'Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
      mono: [
        'ui-monospace',
        'SFMono-Regular',
        'Menlo',
        'Monaco',
        'Consolas',
        '"Liberation Mono"',
        '"Courier New"',
        'monospace',
      ],
    },
    fontSize: {
      '2xs': '.7rem',
      '3xs': '.65rem',
      '4xs': '.6rem',
      'xs': '.75rem',
      'sm': '.875rem',
      'tiny': '.875rem',
      'base': '1rem',
      'lg': '1.125rem',
      'xl': '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '4rem',
      '7xl': '5rem',
    },
    extend: {
      backgroundImage: {
        'm-dashboard-mission-long': "url('/images/mobiles/dashboard-mission-long.png')",
        'm-dashboard-mission-square': "url('/images/mobiles/dashboard-mission-square.png')",
        'm-medals': "url('/images/mobiles/bg-medals.jpg')",
        'm-medals-syariah': "url('/images/mobiles/bg-medals-syariah.jpg')",
        'm-medal-cover-bronze': "url('/images/mobiles/medal-cover-bronze.jpg')",
        'm-medal-cover-silver': "url('/images/mobiles/medal-cover-silver.jpg')",
        'm-medal-cover-gold': "url('/images/mobiles/medal-cover-gold.jpg')",
        'm-medal-cover-platinum': "url('/images/mobiles/medal-cover-platinum.jpg')",
        'm-medal-cover-priority': "url('/images/mobiles/medal-cover-priority.jpg')",
        'm-medal-benefit': "url('/images/mobiles/medal-benefit.jpg')",
        'd-medal-cover': "url('/images/desktop/bg-top-medals.png')",
        'd-medal-cover-bronze': "url('/images/desktop/medal-cover-bronze.png')",
        'd-medal-cover-silver': "url('/images/desktop/medal-cover-silver.png')",
        'd-medal-cover-gold': "url('/images/desktop/medal-cover-gold.png')",
        'd-medal-cover-platinum': "url('/images/desktop/medal-cover-platinum.png')",
        'd-medal-cover-priority': "url('/images/desktop/medal-cover-priority.png')",
        'd-medal-benefit': "url('/images/mobiles/medal-benefit.jpg')"
      }
    },
  },
  variants: {
    extend: {
      backgroundColor: ['checked'],
      borderColor: ['checked'],
    }
  },
  plugins: [
  ],
}
